# NumPy
NumPy is an open-source library that is the universal standard for working with numerical data in Python, and forms the foundation of other libraries like Pandas

NumPy arrays are fixed-size containers of items that are more efficient than Python lists or tuples for data processing.

• They only store a single data type (mixed data types are stored as a string)

• They can be one dimensional or multi-dimensional

• Array elements can be modified, but the array size cannot change

In [1]:
import numpy as np

`np` is the standard alias for the NumPy library

In [2]:
sales = [0, 10, 15, 20, 25, 30]
sales_array = np.array(sales)
print(sales_array)

[ 0 10 15 20 25 30]


NumPy’s array function converts Python lists and tuples into NumPy arrays.

### NumPy arrays
NumPy arrays have these key properties:

• ndim– the number of dimensions (axes) in the array

• shape– the size of the array for each dimension

• size– the total number of elements in the array

• dtype– the data type of the elements in the array


In [3]:
sales = [0, 10, 15, 20, 25, 30]
sales_array = np.array(sales)
print(type(sales_array))

<class 'numpy.ndarray'>


In [6]:
sales = [0, 10, 15, 20, 25, 30]
sales_array = np.array(sales)
print(sales_array.ndim)

1


In [7]:
sales = [0, 10, 15, 20, 25, 30]
sales_array = np.array(sales)
print(sales_array.shape)

(6,)


In [8]:
sales = [0, 10, 15, 20, 25, 30]
sales_array = np.array(sales)
print(sales_array.size)

6


In [9]:
sales = [0, 10, 15, 20, 25, 30]
sales_array = np.array(sales)
print(sales_array.dtype)

int64


Converting a nested list creates a multi-dimensional
array, where each nested list is a dimension
> NOTE: The nested lists must be of equal length

In [10]:
sales = [[0, 10, 15, 20, 25], [30, 35, 40, 45, 50]]
sales_array = np.array(sales)
print(sales_array)

[[ 0 10 15 20 25]
 [30 35 40 45 50]]


In [11]:
print(sales_array.ndim)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.dtype)

2
(2, 5)
10
int64


## ASSIGNMENT: ARRAY BASICS
Hi there, welcome to the Maven MegaMart!

Your resume mentions you have basic Python experience.
Our finance team has been asking us to cut software costs –
can you help us dig into Python as an analysis tool?
I know NumPy is foundational, but not much beyond that.
Can you convert a Python list into a NumPy array and help me
get familiar with their properties?

Thanks!

### The output should be:
> `array([10,20,30,40,50,60,70,80,90,100])`

In [18]:
my_list = []
for x in range(10, 101, 10):
    my_list.append(x)
my_arry = np.array(my_list)
print(my_arry)

[ 10  20  30  40  50  60  70  80  90 100]


In [19]:
print(my_arry.ndim)
print(my_arry.shape)
print(my_arry.size)
print(my_arry.dtype)

1
(10,)
10
int64


### Challenge 1.
#### NumPy Arrays
A NumPy array, `'age_array'` has been created from a list of ages.



Store the size of the array in the variable `'size'`, and the shape of the array in the variable `'shape'`, then print both variables.

In [20]:
import numpy as np

age_list = [22, 34, 57, 65, 87, 19, 44]

age_array = np.array(age_list)

size = age_array.size

shape = age_array.shape

print(size, shape)

7 (7,)


## ARRAY CREATION
As an alternative to converting lists, you can create arrays using functions



*   `ones` Creates an array of ones of a given size, as float by default.

> `np.ones((rows, cols), dtype)`

*   `zeros` Creates an array of zeros of a given size, as float by default.

> `np.zeros((rows, cols), dtype)`

*   `arange` Creates an array of integers with given start & stop values, and a step size (only stop is required, and is not inclusive).

> `np.arange(start, stop, step)`

*   `linspace` Creates an array of floats with given start & stop values with n elements, separated by a consistent step size (stop is inclusive).

> `np.linspace(start, stop, n)`

*   `reshape` Changes an array into the specified dimensions, if compatible.  

> `np.array.reshape(rows, cols)`



In [24]:
np.ones((10,10), dtype='int')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [31]:
even_arr = np.arange(0, 100, 2)
print(even_arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [33]:
even_arr.reshape(5, 10)

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

## RANDOM NUMBER ARRAYS

You can create random number arrays from a variety of distributions using
NumPy functions and methods (great for sampling and simulation!)



*   `default_rng` Creates a random number generator (the seed is for reproducibility).

> `np.default_rng(seed)`

*   `random` Returns n random numbers from a uniform distribution between 0 and 1.

> `rng.random(n)`

*   `normal` Returns n random numbers from a normal distribution with a given mean and standard deviation.

> `rng.normal(mean,stdev,n)`


In [37]:
rng = np.random.default_rng(12345)
random_array = rng.random(10)
random_array

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

> PRO TIP: Even though it’s optional, make sure to set a seed when generating random numbers to
ensure you and others can recreate the work you’ve done (the value for the seed is less important)

In [38]:
rng.integers(1,10,100)

array([7, 3, 9, 9, 7, 7, 2, 1, 3, 4, 1, 8, 5, 7, 2, 3, 2, 7, 7, 2, 7, 1,
       4, 2, 7, 4, 5, 5, 5, 3, 6, 8, 5, 2, 1, 2, 1, 1, 2, 6, 8, 8, 6, 6,
       3, 9, 6, 7, 7, 8, 7, 9, 5, 5, 3, 9, 5, 5, 3, 3, 6, 5, 6, 6, 9, 3,
       7, 9, 5, 3, 3, 4, 6, 3, 8, 4, 1, 1, 1, 6, 4, 3, 6, 1, 5, 6, 1, 2,
       4, 3, 9, 4, 6, 2, 8, 2, 7, 5, 4, 5])

In [39]:
rng.normal(50, 5, 10)

array([49.64364597, 52.37024865, 47.92573119, 50.4885825 , 41.79791082,
       45.71370588, 53.44140894, 44.22735208, 53.25226195, 43.05820024])

### Challenge 2.

Random Number Generation

Create an array `random_ages` that contains 100 random integers representing ages, with each age being between 1 and 100 years inclusive.

Use the `default_rng()` function from NumPy's random module to create a random generator with a seed value of 12345 for reproducibility.

In [48]:
rng = np.random.default_rng(12345)
random_ages = rng.integers(1,101,100)
print(random_ages)

[70 23 79 32 21 80 65 68 99 40 84 34 57 60 22 19 23 68 62 95 71 25 92 95
 74 67 14 10 27 45  8 89 48 70 22 33 12 74 78 23 72  9 40 16 75 35 48 47
 48 27 56 82 50 20  3 13  9 10 13 60 81 86 66 61 34 94 65 73 74 87 71 93
 55 55 26 94 56 50 32 28 64 46 57 67 90 34 69 91 46 26 30 34 63 26 84 36
  7  1  3 63]


### ASSIGNMENT: ARRAY CREATION

Thanks for your help last time – I’m starting to understand
NumPy Arrays!

Are there any NumPy functions that can create arrays so we
don’t have to convert from a Python list? Recreate the array
from the first assignment but make it 5 rows by 2 columns.

Once you’ve done that, create an array of random numbers
between 0 and 1 in a 3x3 shape. One of our data scientists has
been asking about this so I want to make sure it’s possible.

Thanks!

In [51]:
rng = np.random.default_rng(12345)
random_ages = rng.integers(1,101,10)
random_ages.reshape(5,2)

array([[70, 23],
       [79, 32],
       [21, 80],
       [65, 68],
       [99, 40]])

In [53]:
rng = np.random.default_rng(12345)
random_ages = rng.integers(0,2,9)
random_ages.reshape(3,3)

array([[1, 0, 1],
       [0, 0, 1],
       [1, 1, 1]])

> The solution above is mine, and the instructor's solution is below. I know mine is better :)

In [54]:
my_array = np.linspace(10, 100, 10).reshape(5, 2)
print(my_array)

[[ 10.  20.]
 [ 30.  40.]
 [ 50.  60.]
 [ 70.  80.]
 [ 90. 100.]]


In [56]:
from numpy.random import default_rng
rng = default_rng(2022)
random_array = rng.random(9).reshape(3, 3)
print(random_array)

[[0.24742606 0.09299006 0.61176337]
 [0.06066207 0.66103343 0.75515778]
 [0.1108689  0.04305584 0.41441747]]
